import { NextRequest, NextResponse } from "next/server"
import { createAdminClient } from "@/lib/supabase/admin"
import { encrypt } from "@/lib/crypto"
import { verifyExtensionToken } from "@/lib/extension-token"

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization",
}

/**
 * OPTIONS — CORS preflight
 */
export async function OPTIONS() {
  return new NextResponse(null, { status: 204, headers: CORS_HEADERS })
}

/**
 * POST /api/integrations/canvas/bookmarklet
 *
 * Receives Canvas cookies from the bookmarklet running on the Canvas page.
 * Auth: Bearer token (same extension token format, generated by the portal dialog).
 * CORS enabled since the bookmarklet runs on a different origin (canvas.edu).
 *
 * Body: { base_url, cookies: { cookie_name: value, ... }, label? }
 */
export async function POST(request: NextRequest) {
  // Auth via Bearer token
  const authHeader = request.headers.get("authorization")
  if (!authHeader?.startsWith("Bearer ")) {
    return NextResponse.json(
      { error: "Missing authorization header" },
      { status: 401, headers: CORS_HEADERS }
    )
  }

  let userId: string
  try {
    const result = verifyExtensionToken(authHeader.slice(7))
    userId = result.userId
  } catch {
    return NextResponse.json(
      { error: "Invalid or expired token" },
      { status: 401, headers: CORS_HEADERS }
    )
  }

  const body = await request.json().catch(() => null)
  if (!body || typeof body.base_url !== "string" || typeof body.cookies !== "object") {
    return NextResponse.json(
      { error: "Invalid request body" },
      { status: 400, headers: CORS_HEADERS }
    )
  }

  const baseUrl = body.base_url.trim().replace(/\/+$/, "")
  const rawCookies = body.cookies as Record<string, string>
  const label = typeof body.label === "string" ? body.label.trim().slice(0, 100) : "Canvas LMS"

  if (!baseUrl) {
    return NextResponse.json(
      { error: "Canvas URL is required" },
      { status: 400, headers: CORS_HEADERS }
    )
  }

  // Find session cookie (try known names)
  const sessionCookie =
    rawCookies["_normandy_session"] ||
    rawCookies["canvas_session"] ||
    rawCookies["_legacy_normandy_session"] ||
    null

  if (!sessionCookie) {
    return NextResponse.json(
      { error: "No Canvas session cookie found. Make sure you are logged in." },
      { status: 400, headers: CORS_HEADERS }
    )
  }

  // Build credential payload
  const credentials: Record<string, string> = {
    base_url: baseUrl,
    session_cookie: sessionCookie,
  }

  if (rawCookies["_csrf_token"]) {
    credentials.csrf_token = rawCookies["_csrf_token"]
  }
  if (rawCookies["log_session_id"]) {
    credentials.log_session_id = rawCookies["log_session_id"]
  }

  // Encrypt and save
  const encrypted = encrypt(JSON.stringify(credentials))

  const admin = createAdminClient()
  const { error: dbError } = await admin
    .from("user_integrations")
    .upsert(
      {
        user_id: userId,
        provider: "canvas",
        label,
        status: "active",
        credentials: `\\x${Buffer.from(encrypted).toString("hex")}`,
        updated_at: new Date().toISOString(),
      },
      { onConflict: "user_id,provider,label" }
    )

  if (dbError) {
    console.error("[canvas/bookmarklet] DB error:", dbError)
    return NextResponse.json(
      { error: "Failed to save credentials" },
      { status: 500, headers: CORS_HEADERS }
    )
  }

  return NextResponse.json({ success: true }, { headers: CORS_HEADERS })
}
